# Generated by Django 5.0.6 on 2026-02-27 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('capacity_limit', models.PositiveIntegerField(default=100)),
                ('current_count', models.PositiveIntegerField(default=0)),
                ('density_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('camera_url', models.CharField(blank=True, help_text='RTSP URL or webcam index (e.g., 0, 1, rtsp://...)', max_length=500)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CrowdLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_count', models.PositiveIntegerField()),
                ('density_level', models.CharField(max_length=10)),
                ('occupancy_percentage', models.FloatField()),
                ('source', models.CharField(choices=[('AI', 'AI Detection'), ('MANUAL', 'Manual Entry')], default='AI', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='locations.location')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['location', '-timestamp'], name='locations_c_locatio_22dc65_idx')],
            },
        ),
    ]
